#!/bin/sh

case "$1" in
"init")
    if [ ! -z "$(docker ps -qa -f name=ros-devel-$2)" ]; then
        echo "The container is already initialized."
        echo "To use it, run "
        echo "    ros-devel run $2"
        echo "To remove it, run "
        echo "    ros-devel rm $2"
    else
        image="alabate/ros-devel:$2"
        if [ ! -z "$3" ] ; then
            image="$3"
        fi

        echo "ros-devel: Create the container 'ros-devel-$2' with the image '$image'"
        docker run \
            -e USER=$USER -e UID=`id -u $USER` -e GID=`id -g $USER` -e HOME=$HOME -e SHELL=$SHELL \
            -e DISPLAY -e TERM -e HOSTNAME=$2 \
            --privileged \
            -v "/dev:/dev:rw" \
            -v "${HOME}:${HOME}:rw" \
            -v "/tmp/.X11-unix:/tmp/.X11-unix:rw" \
            --net=host \
            --hostname $2 \
            --name ros-devel-$2 \
            --entrypoint /entrypoint.sh \
            -d $image /usr/bin/tail -f /dev/null
    fi
    ;;
"run")
    # Allow docker windows to show on our current X Server
    xhost + >> /dev/null

    # Start the container in case it's stopped
    docker start ros-devel-$2

    # Attach a terminal into the container
    exec docker exec -it ros-devel-$2 /entrypoint.sh
    ;;
"rm")
    docker rm -f ros-devel-$2
    ;;
"stop")
    docker stop ros-devel-$2
    ;;
"list")
    docker ps -a --filter='name=ros-devel-'
    ;;
"save")
    echo "ros-devel: Save the container 'ros-devel-$2' into the image '$3'"
    docker commit ros-devel-$2 $3

    echo "To init a new container with this image, you can do"
    echo "    ros-devel init [container-name] $3"
    ;;
*)
    echo "Usage: ros-devel [command] [arguments]

Available commands:

    ros-devel init [distribution-name]
        Create a new ros-devel container from the given ROS distribution. The container name will be the 'distribution-name'
        Example: ros-devel init lunar

    ros-devel run [container-name]
        Attach a new terminal to a ros-devel container (and start it if necessary)
        Example: ros-devel attach lunar

    ros-devel stop [container-name]
        Stop this running container
        Example: ros-devel stop lunar

    ros-devel rm [container-name]
        Stop and remove the containers from the system
        Example: ros-devel rm lunar

Advanced usage:

    ros-devel init [container-name] [image]
        Create a new ros-devel container from the given docker image (can be a remote one) with 'container-name' as container name
        Example: ros-devel init mylunar alabate/ros-devel:lunar

    ros-devel save [container-name] [image]
        Save the given contaigner to a new image so it can be used later as a new container or pushed to a docker registry.
        Example: ros-devel save lunar myimage
"
    ;;
esac
